# --- !Ups

create table QUOTES (
  ID integer generated by default as identity(start with 1) not null primary key,
  ENGLISH varchar not null,
  DOTHRAKI varchar not null);

insert into QUOTES (ENGLISH, DOTHRAKI) values ('I will kill the men in iron suits', 'Anha vaddrivak mahrazhis fini ondee khogar shiqethi');
insert into QUOTES (ENGLISH, DOTHRAKI) values ('She will speak before me;; until then you will keep yourself quiet', 'Me vastoe hatif anni;; ahhazaan yer nemo vacchaki');

# --- !Downs

drop table QUOTES;
